# Generated by Django 2.1.4 on 2018-12-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20181218_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seen',
            name='movieid',
        ),
        migrations.DeleteModel(
            name='Seen',
        ),
    ]
